#!/bin/sh
# gen_profiles.sh
# Regenerate the committed speclicm*.profile side-files under expected/.
#
# Pipeline (Phase 1 of profile-gated SpecLICM):
#   1. Compile the test with `uscc -EN` to produce an instrumented .bc
#      (the PA2 naive edge profiler instruments every CFG edge).
#   2. Run it through lli.  The instrumented build emits the program's
#      own stdout first, then appends an `EDGE_PROFILE:` text block
#      generated by insertEdgeProfilePrinting.
#   3. Split the `EDGE_PROFILE` block out of the combined output using
#      awk and write it to expected/<name>.profile.
#
# Re-run this script after editing any speclicm*.usc if you need to
# refresh the committed profile data.  The profile files are normally
# committed as test assets, so testSpecLICM.py just reads them.
set -e
cd "$(dirname "$0")"
mkdir -p expected
for usc in speclicm*.usc; do
  name="${usc%.usc}"
  rm -f "${name}.bc"
  ../bin/uscc -EN -b "${usc}"
  ../../bin/lli "${name}.bc" > "${name}.raw" || true
  awk '/=== NAIVE EDGE PROFILING ===/{p=1} p' "${name}.raw" > "expected/${name}.profile"
  rm -f "${name}.bc" "${name}.raw"
  echo "wrote expected/${name}.profile"
done
