#!/usr/bin/env python3
#---------------------------------------------------------
# testSpecLICM.py
#
# Direct IR comparison for the profile-gated SpecLICM pass.  For each
# speclicmNN.usc, runs:
#
#     uscc -spec-licm -profile-file expected/speclicmNN.profile -p speclicmNN.usc
#
# and compares the captured stdout (textual LLVM IR after the SpecLICM
# pipeline) against the committed expected/speclicmNN.output fixture.
# Both the .profile side-files and the .output golden IR are committed
# test data; neither is regenerated by this script.
#
# Style: read expected text, run the compiler, assertMultiLineEqual.
#---------------------------------------------------------
import subprocess
import os

import unittest
uscc = "../bin/uscc"

__unittest = True


class SpecLICMTests(unittest.TestCase):

    def setUp(self):
        self.maxDiff = None
        if not os.path.isfile(uscc):
            raise Exception("Can't run without uscc")

    def checkSpecLICM(self, fileName):
        with open("expected/" + fileName + ".output", "r") as f:
            expectedStr = f.read()
        try:
            resultStr = subprocess.check_output(
                [uscc, "-spec-licm",
                 "-profile-file", "expected/" + fileName + ".profile",
                 "-p", fileName + ".usc"],
                stderr=subprocess.STDOUT,
                text=True)
            self.assertMultiLineEqual(expectedStr, resultStr)
        except subprocess.CalledProcessError as e:
            self.fail("\n" + e.output)

    def test_speclicm01(self): self.checkSpecLICM("speclicm01")
    def test_speclicm02(self): self.checkSpecLICM("speclicm02")
    def test_speclicm03(self): self.checkSpecLICM("speclicm03")
    def test_speclicm04(self): self.checkSpecLICM("speclicm04")
    def test_speclicm05(self): self.checkSpecLICM("speclicm05")
    def test_speclicm06(self): self.checkSpecLICM("speclicm06")
    def test_speclicm07(self): self.checkSpecLICM("speclicm07")
    def test_speclicm08(self): self.checkSpecLICM("speclicm08")
    def test_speclicm09(self): self.checkSpecLICM("speclicm09")
    def test_speclicm10(self): self.checkSpecLICM("speclicm10")
    def test_speclicm11(self): self.checkSpecLICM("speclicm11")
    def test_speclicm12(self): self.checkSpecLICM("speclicm12")
    def test_speclicm13(self): self.checkSpecLICM("speclicm13")
    def test_speclicm14(self): self.checkSpecLICM("speclicm14")
    def test_speclicm15(self): self.checkSpecLICM("speclicm15")
    def test_speclicm16(self): self.checkSpecLICM("speclicm16")
    def test_speclicm17(self): self.checkSpecLICM("speclicm17")
    def test_speclicm18(self): self.checkSpecLICM("speclicm18")
    def test_speclicm19(self): self.checkSpecLICM("speclicm19")
    def test_speclicm20(self): self.checkSpecLICM("speclicm20")
    def test_speclicm21(self): self.checkSpecLICM("speclicm21")
    def test_speclicm22(self): self.checkSpecLICM("speclicm22")
    def test_speclicm23(self): self.checkSpecLICM("speclicm23")
    def test_speclicm24(self): self.checkSpecLICM("speclicm24")
    def test_speclicm25(self): self.checkSpecLICM("speclicm25")
    def test_speclicm26(self): self.checkSpecLICM("speclicm26")


if __name__ == '__main__':
    unittest.main(verbosity=2)
